version: 2

project_name: aqua

before:
  hooks:
    - go mod download

builds:
  - id: aqua
    main: ./cmd/aqua
    binary: aqua
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.buildVersion={{ .Version }} -X main.buildCommit={{ .Commit }} -X main.buildDate={{ .Date }}

archives:
  - id: default
    ids:
      - aqua
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
